### PR TITLE
fixed arguments handling

### PR DESCRIPTION
**Pull request by WMDE-Fisch**

### CODE REVIEW

**Comment by gbirke** [comment]
Why are you changing that like this? Any special bug?
The example modules don't use the star(http://pywikibot.readthedocs.org/en/latest/_modules/scripts/revertbot/)  and it should generally not be necessary to "double-star".

**Comment by WMDE-Fisch** [comment]
It is not necessary that's true but PyCharm's type checker is complaing without the star:

Expected type 'list[unicode]', got 'tuple' instead

**Comment by WMDE-Fisch** [comment]
cant merge it myself. if you are fine with the changes would you merge it @gbirke ?

**Comment by gbirke** [comment]
I'd like to experiment with other syntax to avoid the weird-looking star syntax. Will get back to that ...

**Pull request merged**
