### PR TITLE
Refactor ArticleIterator callbacks

### PR DESCRIPTION
**Pull request by gbirke**
Callbacks are now put into their own class. This reduces the number of constructor params and the number of checks in ArticleIterator.

### CODE REVIEW

**Comment by gbirke** [comment]
I’m not sure if the dispatch mechanism of ArticleIteratorCallbacks is ok but wanted to observe the Law of Demeter by not calling e.g. 

```self.callbacks.logging(some, params)```

inside of `ArticleIterator`. But is 

`self.callbacks("logging", some, params)` 

really better?

**Comment by JeroenDeDauw** [comment]
I think `self.callbacks.logging(some, params)` is much better than `self.callbacks("logging", some, params)`.

You're right your refactoring introduces a violation of the LoD by solving a SRP issue. These two are often at odds, and generally SRP seems to be the more important one. I remember the www.destroyallsoftware.com guy saying something similar, though can't remember where.

Not sure you are actually avoiding the LoD violation with what you are doing. Perhaps per exact definition, though not in intended meaning.

**Comment by JeroenDeDauw** [comment]
Ugh. Should not do review when tired... `self.field.method()` is not a LoD violation. Local vars and fields can be talked to, so you can omit the `self.` part. The "one dot per line" makes more sense in java, where you don't need to explicitly refer to self. This would be a violation: `notSelf.field.method()`

**Comment by wmde-manicki** [comment]
+1

**Pull request merged**
